# Do not modify this file! It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead. [cite: 37, 38]
{ config, lib, pkgs, modulesPath, ... }: # Definiert die Funktionsargumente: Zugriff auf System-Konfig, Bibliotheken, Pakete und Modulpfade. [cite: 38]

{
  imports = # Startet den Import-Block für externe Konfigurations-Schnipsel. [cite: 38]
    [ (modulesPath + "/installer/scan/not-detected.nix") # Importiert Standard-Erkennungslogik für Hardware, die nicht automatisch gefunden wurde. [cite: 38]
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ]; # Lädt kritische Treiber (SATA, Speicher, Tastatur) direkt in der Ramdisk für den Bootvorgang. [cite: 39]
  boot.initrd.kernelModules = [ ]; # Platzhalter für Kernel-Module, die sehr früh in der Boot-Phase benötigt werden. [cite: 39]
  boot.kernelModules = [ "kvm-intel" ]; # Aktiviert die Hardware-Virtualisierung für Intel-CPUs (z.B. für dein PiXeL-Lab). [cite: 39]
  boot.extraModulePackages = [ ]; # Ermöglicht das Hinzufügen von Kernel-Modulen außerhalb des Standard-Kernels. [cite: 40]

  fileSystems."/" = # Definiert den Einhängepunkt für das Wurzelverzeichnis (Root). [cite: 40]
    { device = "/dev/disk/by-uuid/d2601b3b-5d9f-4c18-b89a-d6b3b0d43434"; # Nutzt die eindeutige UUID der Partition für einen stabilen Mount-Punkt. [cite: 40]
      fsType = "ext4"; # Legt das EXT4-Dateisystem für hohe Datensicherheit fest. [cite: 40]
    };

  fileSystems."/boot" = # Definiert den Mount-Punkt für die EFI-Boot-Partition. [cite: 41]
    { device = "/dev/disk/by-uuid/99F0-7AE3"; # Die eindeutige ID der EFI-Partition für den Bootloader. [cite: 41]
      fsType = "vfat"; # Verwendet das VFAT-Format als globalen EFI-Standard. [cite: 41]
      options = [ "fmask=0077" "dmask=0077" ]; # Setzt strikte Zugriffsberechtigungen (nur Root). [cite: 41]
    };

  swapDevices = [ ]; # Aktuell kein Auslagerungsspeicher definiert; das System nutzt rein den physischen RAM. [cite: 42]

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; # Legt die 64-Bit Intel/AMD Architektur als Plattform fest. [cite: 42]
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; # Lädt CPU-Sicherheitsupdates gegen Hardware-Lücken wie Spectre. [cite: 42]
  services.usbmuxd.enable = true; # Aktiviert die Kommunikation mit Apple-Geräten für USB-Tethering. [cite: 7]

  /* * 📜 ARCHITEKTEN-NOTIZ FÜR DIE COMMUNITY:
   * ----------------------------------------
   * Dieses System (PiXeLOs) folgt einer strikten Hardware-Logik,
   * um auf dem realen Packard Bell / Intel System maximale Stabilität zu bieten.
   *
   * 🛠️ INITRD MODULE:
   * Die geladenen Treiber (ahci, sd_mod) sind die "Überlebens-Kits".
   * Ohne sie würde der Kernel die Festplatte beim Booten nicht finden. [cite: 39]
   *
   * 🆔 UUID-IDENTITÄT:
   * Wir nutzen UUIDs statt Gerätenamen (/dev/sda). Das garantiert, dass
   * PiXeLOs immer von der richtigen Partition bootet, selbst wenn
   * externe USB-Sticks die Reihenfolge durcheinanderbringen. [cite: 40, 41]
   *
   * 🧠 CPU MICROCODE:
   * Das "Betriebssystem der CPU". Es schließt Hardware-Lücken direkt
   * im Prozessor und hält die Intel-Architektur sicher. [cite: 42]
   *
   * 📱 USBMUXD (THE ARCHITECT'S BRIDGE):
   * Ermöglicht Apple USB-Tethering. Damit bleibt das System auch ohne
   * WLAN-Karte mobil und online. [cite: 7, 39]
   */
}
